//**************************************************************************
// Name: Krunal Patel
// NetId: krp356
// Purpose: Parsing Cpp file
//**************************************************************************
#ifdef _MSC_VER
#define _CRT_SECURE_NO_WARNINGS
#endif

#include <stdlib.h>
#include <iostream>
#include "lexer.h"
#include "parser.h"
 
using namespace std;

int nextToken = 0;            // hold nextToken returned by lex


int lex() {
  nextToken = yylex();
  // if( nextToken == TOK_EOF ) {
  //   yytext[0] = 'E'; yytext[1] = 'O'; yytext[2] = 'F'; yytext[3] = 0;   
  // }

  return nextToken;
}


// Which tree level are we currently in?  
static int level = 0;

// Feel free to use a different data structure for the symbol table (list of
// variables declared in the program) but you will have to adjust the code in
// main() to print out the symbol table after a successful parse
set<string> symbolTable; // Symbol Table




//*****************************************************************************
// Indent to reveal tree structure
string psp(void) { // Stands for p-space, but I want the name short
  string str("");
  for(int i = 0; i < level; i++)
    str += "|  ";
  return str;
}
//*****************************************************************************
// Report what we found
void output(string what) {
  cout << psp() << "found |" << yytext << "| " << what << endl;
}

void output_string_lit() {
  cout << psp() << yytext << endl;
}

void output_variable(string what, string what2) {
  cout << psp() << "-- idName: |"<< what << "| idType: |"<< what2 <<"| --" << endl;
}
//*****************************************************************************
// Forward declarations of FIRST_OF functions.  These check whether the current 
// token is in the FIRST set of a production rule.
bool first_of_program(void);
bool first_of_block(void);
bool first_of_statement(void);
bool first_of_assignment(void);
bool first_of_compound(void);

bool first_of_expression(void);
bool first_of_simple_expression(void);
bool first_of_term(void);
bool first_of_factor(void);
//*****************************************************************************
// Parses strings in the language generated by the rule:
// <program> → TOK_PROGRAM TOK_IDENT TOK_SEMICOLON <block>

// Regular functions

void program() 
{
   
    if (!first_of_program()) // Check for PROGRAM
        throw "3: 'PROGRAM' expected";
    if (nextToken == TOK_PROGRAM) {
      output("PROGRAM");
      lex();
     
    }
    cout << psp() << "enter <program>" << endl;
    ++level;
   
    // TODO: finish this parsing function...
    
    if (nextToken == TOK_IDENT) {
      output("IDENTIFIER");
      lex();
    }
    else {
      throw "2: identifier expected";
    }
    if (nextToken == TOK_SEMICOLON) {
      output("SEMICOLON");
      lex();
    }
    else {
      throw "14: ';' expected";
    }
    block();
    --level;
    cout << psp() << "exit <program>" << endl;
    
}
// <block> -> TOK_BEGIN compound
void block() {
    if (!first_of_block())
      throw "18: error in declaration part OR 17: 'BEGIN' expected";
    output("BLOCK");
    
    cout << psp() << "enter <block>" << endl;
   
    ++level;
    if (nextToken == TOK_VAR) {
      lex();
      variable();
      
    }
    else if (nextToken == TOK_BEGIN) {
      
      
    }
    
    compound();
   
   
    
    --level;
    cout << psp() << "exit <block>" << endl;
}

void variable() {
  if (nextToken == TOK_IDENT) {
    output("IDENTIFIER");
    string var_name = yytext;
    string var_type = "";
    lex();
    
    if (nextToken == TOK_COLON) {
      output("COLON");
      lex();
      if (nextToken == TOK_INTEGER || nextToken == TOK_REAL) {
        output("TYPE");
        var_type = yytext;
      }
      else {
        throw "10: error in type";
      }
      lex();
      if (nextToken == TOK_SEMICOLON) {
        output("SEMICOLON");
        
      }
      else {
        throw "14: ';' expected";
      }
      output_variable(var_name, var_type);
      if (!symbolTable.insert(var_name).second) {
        throw "101: identifier declared twice";
      }
      lex();
      if (nextToken == TOK_IDENT) {
          variable();
      }
    }
    else {
      throw "5: ':' expected";
    }
  }
  else {
    throw "2: identifier expected";
  }                  
}

void statement() {
  output("STATEMENT");
  if (!first_of_statement){ 
    throw "900: illegal type of statement";
  }
  if (nextToken == TOK_WRITE) {
    write();
  }
  else if (nextToken == TOK_IDENT) {
    assignment();
  } 
  else if (nextToken == TOK_BEGIN) {
    compound();
  }
  else if (nextToken == TOK_READ) {
    read();
  }
  else if (nextToken == TOK_IF) {
    if_statement();
  }
  else if (nextToken == TOK_WHILE) {
    while_statement();
  }
 
} 


void expression() {
  output("EXPRESSION");
  cout << psp() << "enter <expression>" << endl;
  ++level;
  simple_expression();
  if (first_of_expression()){ 
    if (nextToken == TOK_EQUALTO) {
      output("EQUALTO");
      output_string_lit();
    }
    else if (nextToken == TOK_GREATERTHAN) {
      output("GREATERTHAN");
      output_string_lit();
    }
    else if (nextToken == TOK_LESSTHAN) {
      output("LESSTHAN");
      output_string_lit();
    }
    else if (nextToken == TOK_NOTEQUALTO) {
      output("NOTEQUALTO");
      output_string_lit();
    }
    lex();
    // if (first_of_simple_expression()) {
    if (first_of_factor()) {
      simple_expression();
    }
    else {
       throw "144: illegal type of expression";
    }
  }
  
  --level;
  cout << psp() << "exit <expression>" << endl;
}

void simple_expression() {
  output("SIMPLE_EXP");
  cout << psp() << "enter <simple_exp>" << endl;
  ++level;
  bool isValid = true;
  while (isValid) {
      if (!first_of_factor()) {
        throw "901: illegal type of simple expression";
      }
      term();
      if (first_of_simple_expression()) {
        if (nextToken == TOK_PLUS) {
          output("PLUS");
          output_string_lit();
          lex();
        }
        else if (nextToken == TOK_MINUS) {
          output("MINUS");
          output_string_lit();
          lex();
        }
        else if (nextToken == TOK_OR) {
          output("OR");
          output_string_lit();
          lex();
        }
        
      }
      else {
       
        isValid = false;
      }
    }
  --level;
  cout << psp() << "exit <simple_exp>" << endl;
}

void term() {
  output("TERM");
  cout << psp() << "enter <term>" << endl;
  ++level;
 
  bool isValid = true;
  while (isValid) {
    if (!first_of_factor()) {
       throw "902: illegal type of term";
    }
    factor();
    lex();
    if (first_of_term()) {
      if (nextToken == TOK_MULTIPLY) {
        output("MULTIPLY");
        output_string_lit();
        lex();
      }
      else if (nextToken == TOK_DIVIDE) {
        output("DIVIDE");
        output_string_lit();
        lex();
      }
      else if (nextToken == TOK_AND) {
        output("AND");
        output_string_lit();
        lex();
      }
      if (!first_of_factor()) {
        throw "902: illegal type of term";
      }
    } else {
      isValid = false;
    }
  }
  --level;
  cout << psp() << "exit <term>" << endl;

}

void factor() {
  output("FACTOR");
  cout << psp() << "enter <factor>" << endl;
  ++level;
  if (!first_of_factor){ 
    throw "903: illegal type of factor";
  }
  if (nextToken == TOK_INTLIT) {
    output("INTLIT");
    output_string_lit();
    
  }
  else if (nextToken == TOK_FLOATLIT) {
    output("FLOATLIT");
    output_string_lit();
    
  }
  else if (nextToken == TOK_IDENT) {
    output("IDENTIFIER");
    output_string_lit();
    if (symbolTable.find(yytext) == symbolTable.end()) {
      throw "104: identifier not declared";
    }
    
  }
  else if (nextToken == TOK_OPENPAREN) {
    output("OPENPAREN");
    output_string_lit();
    lex();
    expression();
    if (nextToken == TOK_CLOSEPAREN) {
      output("CLOSEPAREN");
    }
    else {
      throw "4: ')' expected";
    }
  }
  else if (nextToken == TOK_NOT) {
    output("NOT");
    lex();
    factor();
    
  }
  else if (nextToken == TOK_MINUS) {
    output("MINUS");
    output_string_lit();
    lex();
    factor();
    
  }
  --level;
  cout << psp() << "exit <factor>" << endl;
}

// statement functions

void compound() {
  if (!first_of_compound) {
    throw "17: 'BEGIN' expected";
  }
  if (nextToken == TOK_BEGIN) {
      output("BEGIN");
      lex();   
  }
  cout << psp() << "enter <compound_stmt>" << endl;
  ++level;
  while (first_of_statement()) {
    
    statement();
    if (nextToken == TOK_SEMICOLON) {
      output("SEMICOLON");
      lex();
    }
    else {
      break;
    }
  }
  --level;
  if (nextToken == TOK_END) {
    // --level;
    output("END");
    lex();
    // ++level;
  }
  else {
    throw "13: 'END' expected";
  }

  
  
  cout << psp() << "exit <compound_stmt>" << endl;
 
}

void assignment() {
  cout << psp() << "enter <assignment>" << endl;
  ++level;
  output("IDENTIFIER");
  output_string_lit();
  if (symbolTable.find(yytext) == symbolTable.end()) {
    throw "104: identifier not declared";
  };
  lex();    
  if (nextToken == TOK_ASSIGN) {
    output("ASSIGN");
    lex();
    expression();
  }
  else {
    throw "51: ':=' expected";
  }
  --level;
  cout << psp() << "exit <assignment>" << endl;
}

void write() {
  lex();
  cout << psp() << "enter <write>" << endl;
  ++level;
  if (nextToken == TOK_OPENPAREN) {
    output("OPENPAREN");
    lex();
    if (nextToken == TOK_IDENT) {
      output("WRITE");
      output_string_lit();
      if (symbolTable.find(yytext) == symbolTable.end()) {
        throw "104: identifier not declared";
      };
      lex();
      
    }
    else if (nextToken == TOK_STRINGLIT) {
      output("WRITE");
      output_string_lit();
      lex();
    }
    else {
      throw "134: illegal type of operand(s)";
    }
    if (nextToken == TOK_CLOSEPAREN) {
      output("CLOSEPAREN");
      lex();
    }
    else {
      throw "4: ')' expected";
    }
   }
  else {
    throw "9: '(' expected";
  }
  --level;
  cout << psp() << "exit <write>" << endl;   
}


void read() {
  lex();
  cout << psp() << "enter <read>" << endl;
  ++level;
  if (nextToken == TOK_OPENPAREN) {
    output("OPENPAREN");
    lex();
    if (nextToken == TOK_IDENT) {
      output("IDENTIFIER");
      output_string_lit();
      if (symbolTable.find(yytext) == symbolTable.end()) {
        throw "104: identifier not declared";
      };
      lex();
    }
    else {
      throw "2: identifier expected";
    }
    if (nextToken == TOK_CLOSEPAREN) {
      output("CLOSEPAREN");
      lex();
    }
    else {
      throw "4: ')' expected";
    }
   }
  else {
    throw "9: '(' expected";
  }
  --level;
  cout << psp() << "exit <read>" << endl;   
}

void if_statement() {
  lex();
  cout << psp() << "enter <if>" << endl;
  ++level;
  expression();
  if (nextToken == TOK_THEN) {
    output("THEN");
    lex();
    statement();
     
    if (nextToken == TOK_ELSE) {
  
      --level;
      output("ELSE");
      cout << psp() << "enter <else>" << endl;
      ++level;
     // ++level;
      lex();
      statement();
      
      // --level;
      // cout << psp() << "exit <else>" << endl;
      
    }
  } 
  else {
    throw "52: 'THEN' expected";
  }
   --level;
  cout << psp() << "exit <if>" << endl;   
}

void while_statement() {
  lex();
  cout << psp() << "enter <while>" << endl;
  ++level;
  expression();
  statement();
   --level;
  cout << psp() << "exit <while>" << endl;   
}
// first_of functions

bool first_of_program(void) {
    return nextToken == TOK_PROGRAM;
}

bool first_of_block(void) {
  return nextToken == TOK_VAR || nextToken == TOK_BEGIN;
}

bool first_of_compound(void) {
  return nextToken == TOK_BEGIN;
}

bool first_of_statement(void) {
  return nextToken == TOK_IDENT || nextToken == TOK_BEGIN || nextToken == TOK_IF || nextToken == TOK_WHILE || nextToken == TOK_WRITE || nextToken == TOK_READ;
}

bool first_of_assignment(void) {
  return nextToken == TOK_IDENT;
}
bool first_of_expression(void) {
  return nextToken == TOK_EQUALTO || nextToken == TOK_GREATERTHAN|| nextToken == TOK_LESSTHAN || nextToken == TOK_NOTEQUALTO;
}

bool first_of_simple_expression(void) {
  return nextToken == TOK_PLUS || nextToken == TOK_MINUS || nextToken == TOK_OR;
}

bool first_of_term(void) {
  return nextToken == TOK_AND || nextToken == TOK_MULTIPLY || nextToken == TOK_DIVIDE;
}

bool first_of_factor(void) {
  return nextToken == TOK_INTLIT || TOK_FLOATLIT || nextToken == TOK_INTEGER || nextToken == TOK_IDENT || nextToken == TOK_OPENPAREN || nextToken == TOK_NOT || nextToken == TOK_MINUS;
}
